services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: forklift_demo:jazzy
    container_name: forklift_demo_sim
    network_mode: host
    ipc: host
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - .:/ws
      - colcon_build_jazzy:/ws/build
      - colcon_install_jazzy:/ws/install
      - colcon_log_jazzy:/ws/log
    command: >
      bash -lc "
      colcon build --symlink-install --packages-up-to forklift_demo_description &&
      source /ws/install/setup.bash &&
      ros2 launch forklift_demo_description sim_followpath.launch.py launch_rviz:=false"

  rviz:
    image: forklift_demo:jazzy
    container_name: forklift_demo_rviz
    user: "1000:1000"
    depends_on:
      - sim
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: "1"
      HOME: /tmp/rviz-home
      ROS_LOG_DIR: /tmp/rviz-home/.ros/log
      XDG_RUNTIME_DIR: /tmp/runtime-user
      XAUTHORITY: /tmp/.Xauthority
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - .:/ws
      - colcon_install_jazzy:/ws/install:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/dev/null}:/tmp/.Xauthority:ro
    command: >
      bash -lc "
      mkdir -p /tmp/rviz-home/.ros/log &&
      mkdir -p /tmp/runtime-user &&
      chmod 700 /tmp/runtime-user &&
      until [ -f /ws/install/setup.bash ]; do sleep 1; done &&
      source /ws/install/setup.bash &&
      ros2 run rviz2 rviz2 -d /ws/src/forklift_demo_description/rviz/demo.rviz"

  rqt:
    image: forklift_demo:jazzy
    container_name: forklift_demo_rqt
    user: "1000:1000"
    depends_on:
      - sim
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: "1"
      HOME: /tmp/rqt-home
      ROS_LOG_DIR: /tmp/rqt-home/.ros/log
      XDG_RUNTIME_DIR: /tmp/runtime-user
      XAUTHORITY: /tmp/.Xauthority
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - .:/ws
      - colcon_install_jazzy:/ws/install:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/dev/null}:/tmp/.Xauthority:ro
    command: >
      bash -lc "
      mkdir -p /tmp/rqt-home/.ros/log &&
      mkdir -p /tmp/runtime-user &&
      chmod 700 /tmp/runtime-user &&
      until [ -f /ws/install/setup.bash ]; do sleep 1; done &&
      source /ws/install/setup.bash &&
      ros2 run rqt_robot_steering rqt_robot_steering --ros-args
      -p default_topic:=/cmd_vel
      -p default_vx_min:=-0.85
      -p default_vx_max:=0.85
      -p default_vw_min:=-1.0
      -p default_vw_max:=1.0"

volumes:
  colcon_build_jazzy:
  colcon_install_jazzy:
  colcon_log_jazzy:
