services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: forklift_demo:humble
    container_name: forklift_demo_sim
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: /root/.Xauthority
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/dev/null}:/root/.Xauthority:ro
    command: >
      ros2 launch forklift_demo_description sim_followpath.launch.py
      launch_rviz:=false

  rviz:
    image: forklift_demo:humble
    container_name: forklift_demo_rviz
    depends_on:
      - sim
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: /root/.Xauthority
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/dev/null}:/root/.Xauthority:ro
    command: >
      ros2 run rviz2 rviz2
      -d /ws/install/forklift_demo_description/share/forklift_demo_description/rviz/demo.rviz
