json_map_visualizer:
  ros__parameters:
    use_sim_time: true
    map_service_name: /robot_data/map/get_map
    refresh_service_name: /robot_data/map/visualize
    marker_topic: /json_map/markers
    frame_id: map
    publish_period_sec: 0.0
    deduplicate_bidirectional_paths: true
    draw_labels: true
    point_scale: 0.14
    path_width: 0.045
