scan_sector_filter:
  ros__parameters:
    use_sim_time: true
    input_scan_topic: /scan_raw
    output_scan_topic: /scan
    blind_sector_center_deg: 0.0
    blind_sector_half_width_deg: 32.0

scan_left_sector_filter:
  ros__parameters:
    use_sim_time: true
    input_scan_topic: /scan_left
    output_scan_topic: /scan_left_limited
    # Keep [-90, 180] by blinding [-180, -90].
    blind_sector_center_deg: -135.0
    blind_sector_half_width_deg: 45.0

scan_right_sector_filter:
  ros__parameters:
    use_sim_time: true
    input_scan_topic: /scan_right
    output_scan_topic: /scan_right_limited
    # Keep [-180, 90] by blinding [90, 180].
    blind_sector_center_deg: 135.0
    blind_sector_half_width_deg: 45.0

scan_rear_sector_filter:
  ros__parameters:
    use_sim_time: true
    input_scan_topic: /scan_raw
    output_scan_topic: /scan_rear_limited
    # Keep [-45, 45] by blinding everything else.
    blind_sector_center_deg: 180.0
    blind_sector_half_width_deg: 135.0
