collision_monitor:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "tracking_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.2
    source_timeout: 1.0
    stop_pub_timeout: 0.5

    polygons: ["PolygonStop", "PolygonSlow"]

    PolygonStop:
      type: "polygon"
      points: [0.80, 0.45, 0.80, -0.45, 0.05, -0.45, 0.05, 0.45]
      action_type: "stop"
      max_points: 3
      visualize: true
      polygon_pub_topic: "collision_monitor/polygon_stop"
      enabled: true

    PolygonSlow:
      type: "polygon"
      points: [1.30, 0.70, 1.30, -0.70, 0.05, -0.70, 0.05, 0.70]
      action_type: "slowdown"
      slowdown_ratio: 0.35
      max_points: 3
      visualize: true
      polygon_pub_topic: "collision_monitor/polygon_slowdown"
      enabled: true

    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: true
