collision_monitor:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.2
    source_timeout: 1.0
    stop_pub_timeout: 2.0

    polygons: ["PolygonStop", "PolygonSlow"]

    PolygonStop:
      type: "polygon"
      action_type: "stop"
      min_points: 4
      visualize: true
      polygon_pub_topic: "collision_monitor/polygon_stop"
      enabled: true
      points: "[[1.73, 0.45], [1.73, -0.45], [0.98, -0.45], [0.98, 0.45]]"

    PolygonSlow:
      type: "polygon"
      points: "[[2.23, 0.70], [2.23, -0.70], [0.98, -0.70], [0.98, 0.70]]"
      action_type: "slowdown"
      slowdown_ratio: 0.35
      min_points: 4
      visualize: true
      polygon_pub_topic: "collision_monitor/polygon_slowdown"
      enabled: true

    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: true
