route_server:
  ros__parameters:
    use_sim_time: true
    route_frame: map
    global_frame: map
    base_frame: base_link
    graph_filepath: /tmp/forklift_demo_route_graph.geojson
    graph_file_loader: "GeoJsonGraphFileLoader"
    path_density: 0.05
    enable_nn_search: true
    num_nearest_nodes: 5
    max_nn_search_iterations: 10000
    max_iterations: 0
    max_planning_time: 2.0
    smooth_corners: false
    smoothing_radius: 0.5
    prune_goal: true
    min_prune_dist_from_start: 0.1
    min_prune_dist_from_goal: 0.15
    boundary_radius_to_achieve_node: 0.05
    radius_to_achieve_node: 0.25
    edge_cost_functions: ["DistanceScorer"]
    operations: ["AdjustSpeedLimit", "ReroutingService"]

    GeoJsonGraphFileLoader:
      plugin: "nav2_route::GeoJsonGraphFileLoader"

    DistanceScorer:
      plugin: "nav2_route::DistanceScorer"

    AdjustSpeedLimit:
      plugin: "nav2_route::AdjustSpeedLimit"

    ReroutingService:
      plugin: "nav2_route::ReroutingService"
