image_transport: raw
family: 36h11
size: 0.24
profile: false
max_hamming: 2
threads: 2
decimate: 1.0
blur: 0.0
refine-edges: 1
debug: 0
z_up: false
pose_estimation_method: pnp
detector:
  threads: 2
  decimate: 1.0
  blur: 0.0
  refine: 1
  sharpening: 0.25
  debug: 0
tag_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
tag_frames:
  [
    camera_pallet_b_south_00_tag,
    camera_pallet_b_south_01_tag,
    camera_pallet_b_south_02_tag,
    camera_pallet_b_south_03_tag,
    camera_pallet_b_south_04_tag,
    camera_pallet_b_south_05_tag,
    camera_pallet_b_south_06_tag,
    camera_pallet_b_south_07_tag,
    camera_pallet_b_south_08_tag,
    camera_pallet_b_south_09_tag,
    camera_pallet_b_south_10_tag,
    camera_pallet_b_south_11_tag,
    camera_pallet_b_north_00_tag,
    camera_pallet_b_north_01_tag,
    camera_pallet_b_north_02_tag,
    camera_pallet_b_north_03_tag,
    camera_pallet_b_north_04_tag,
    camera_pallet_b_north_05_tag,
    camera_pallet_b_north_06_tag,
    camera_pallet_b_north_07_tag,
    camera_pallet_b_north_09_tag,
    camera_pallet_b_north_10_tag,
    camera_pallet_b_north_11_tag,
  ]
tag_sizes: [0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24]
tag:
  ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
  frames:
    [
      camera_pallet_b_south_00_tag,
      camera_pallet_b_south_01_tag,
      camera_pallet_b_south_02_tag,
      camera_pallet_b_south_03_tag,
      camera_pallet_b_south_04_tag,
      camera_pallet_b_south_05_tag,
      camera_pallet_b_south_06_tag,
      camera_pallet_b_south_07_tag,
      camera_pallet_b_south_08_tag,
      camera_pallet_b_south_09_tag,
      camera_pallet_b_south_10_tag,
      camera_pallet_b_south_11_tag,
      camera_pallet_b_north_00_tag,
      camera_pallet_b_north_01_tag,
      camera_pallet_b_north_02_tag,
      camera_pallet_b_north_03_tag,
      camera_pallet_b_north_04_tag,
      camera_pallet_b_north_05_tag,
      camera_pallet_b_north_06_tag,
      camera_pallet_b_north_07_tag,
      camera_pallet_b_north_09_tag,
      camera_pallet_b_north_10_tag,
      camera_pallet_b_north_11_tag,
    ]
  sizes: [0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24]
