apriltag_image_gate:
  ros__parameters:
    input_image_topic: /camera/image
    input_camera_info_topic: /camera/camera_info
    output_image_topic: /apriltag_detector/image
    output_camera_info_topic: /apriltag_detector/camera_info
    service_name: /apriltag_detector/control
    enabled: false
    publish_rate_hz: 5.0
    restamp_with_now: true
